export const leadStatus = {
    CONTACTED: "CONTACTED",
    QUALIFIED: "QUALIFIED",
    UNQUALIFIED: "UNQUALIFIED",
    ASSIGNED_TO_GIS: "ASSIGNED_TO_GIS",
    PENDING_WITH_REASON: "PENDING_WITH_REASON",
    CALL_BACK: "CALL_BACK",
    SUSPEND_LEAD: "SUSPEND_LEAD",
    NOT_CLOSED: "NOT_CLOSED",
    CUSTOMER_DETAILS_CAPTURED: "CUSTOMER_DETAILS_CAPTURED",
    PENDING_PAYMENT: "PENDING_PAYMENT",
    PAYMENT_COMPLETED:"PAYMENT_COMPLETED", 
    KYC_PENDING: "KYC_PENDING",
    OPEN: "OPEN",
    KYC_COMPLETED: "KYC_COMPLETED",
    KYC_UPDATED: "KYC_UPDATED",
    LINK_SHARED: "LINK_SHARED",
}
export const gisStatus={
    FEASIBLE:"FEASIBLE",
    NOT_FEASIBLE:"NOT_FEASIBLE",
    INCORRECT_LOCATION:"INCORRECT_LOCATION",
}

